# Generated by Django 2.1.1 on 2018-09-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sit', models.CharField(choices=[('REP', 'Reprovado por falta'), ('ATV', 'Ativo')], default='ATV', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=55)),
                ('id_subscription', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('hours', models.IntegerField()),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(to='api.Subject'),
        ),
    ]
