# Generated by Django 2.1.1 on 2018-09-29 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180928_2141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faul',
            new_name='Fault',
        ),
    ]
