# Generated by Django 2.1.1 on 2018-09-29 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180928_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fault',
            options={'verbose_name': 'Falta'},
        ),
        migrations.RemoveField(
            model_name='fault',
            name='fauts',
        ),
        migrations.AddField(
            model_name='fault',
            name='faults',
            field=models.IntegerField(default=None, verbose_name='faltas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fault',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject', verbose_name='Disciplina'),
        ),
    ]
