# Generated by Django 2.1.1 on 2018-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('ES', 'Engenharia de Software'), ('CC', 'Ciências da Computação'), ('EP', 'Engenharia da Produção'), ('EC', 'Engenharia Civil'), ('EM', 'Engenharia Mecânica')], max_length=30),
        ),
    ]
