# Generated by Django 2.1.1 on 2018-10-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180929_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='day',
            field=models.DateField(auto_now=True),
        ),
    ]
