# Generated by Django 2.1.1 on 2018-10-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fault_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='day',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='faults',
            field=models.IntegerField(verbose_name='Faltas'),
        ),
    ]
