# Generated by Django 2.1.2 on 2018-11-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181004_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.AlterField(
            model_name='subject',
            name='hours',
            field=models.IntegerField(default=64, verbose_name='horas'),
        ),
    ]
