# Generated by Django 2.1.2 on 2018-11-02 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181102_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('Engenharia de Software', 'Engenharia de Software'), ('Ciências da Computação', 'Ciências da Computação'), ('Engenharia da Produção', 'Engenharia da Produção'), ('Engenharia Civil', 'Engenharia Civil'), ('Engenharia Mecânica', 'Engenharia Mecânica')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('ES', 'Engenharia de Software'), ('CC', 'Ciências da Computação'), ('EP', 'Engenharia da Produção'), ('EC', 'Engenharia Civil'), ('EM', 'Engenharia Mecânica')], max_length=30, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Teacher', verbose_name='Professor'),
        ),
    ]
