# Generated by Django 2.1.2 on 2018-11-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_present'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Present',
            new_name='Attendance',
        ),
    ]
