# Generated by Django 2.1.2 on 2018-11-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_subscription',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False, verbose_name='matricula'),
        ),
    ]
