# Generated by Django 2.1.2 on 2018-11-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20181109_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_subscription',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='matricula'),
        ),
    ]
