# Generated by Django 2.1.2 on 2018-11-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20181109_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='name',
            field=models.CharField(default='Fundamentos da Programação', max_length=55),
            preserve_default=False,
        ),
    ]
