# Generated by Django 2.1.2 on 2018-11-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20181110_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='testeusuario',
            name='name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
