# Generated by Django 2.1.2 on 2018-11-11 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_testeusuario_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name': 'Turma'},
        ),
        migrations.RemoveField(
            model_name='fault',
            name='subject',
        ),
        migrations.AddField(
            model_name='fault',
            name='turma',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='api.Turma', verbose_name='Turma'),
            preserve_default=False,
        ),
    ]
