# Generated by Django 2.1.2 on 2018-11-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20181110_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='faults',
            field=models.IntegerField(default=2, verbose_name='Faltas'),
        ),
    ]
